FROM ruby:3.1.1

ARG SSH_PUB_KEY

ENV RAILS_ENV=development
ENV NOKOGIRI_USE_SYSTEM_LIBRARIES=1

RUN apt-get update && \
    apt-get install -y openssh-server cron build-essential libpq-dev libxml2-dev libxslt1-dev zlib1g-dev && \
    mkdir -p /root/.ssh && \
    echo "$SSH_PUB_KEY" > /root/.ssh/authorized_keys

WORKDIR /budoman-backend
COPY . /budoman-backend/
RUN bundle config set force_ruby_platform true && \
    bundle install

ENTRYPOINT ["/bin/sh", "-c", "chmod u+x /budoman-backend/bin/start-development-container.sh && /budoman-backend/bin/start-development-container.sh"]
